### ISSUE TITLE
Mise en place Wireframe MVP

### ISSUE THREAD

**Issue by jsamouh** [jordscream/cupbird#1]
Mise en place Wireframe MVP

**Comment by jordscream** [comment]
![capture d ecran 2016-06-27 a 16 34 57](https://cloud.githubusercontent.com/assets/616999/16516739/e8a55af8-3f79-11e6-9a14-f00371d67cab.png)

**Comment by jsamouh** [comment]
[DECATH SA Tableau de garanties GARANTIES  01012016-1.pdf](https://github.com/jordscream/cupbird/files/343126/DECATH.SA.Tableau.de.garanties.GARANTIES.01012016-1.pdf)
